#!/usr/bin/env node
var sys = require('sys');
var exec = require('child_process').exec;

var colors = require('colors');

try{
  arg = (process.argv[2] !== undefined)? ' '+process.argv[2] : '';
  exec('./bin/stale.sh'+arg
    , function (error, stdout, stderr) {
    console.log(stdout);
    if(stderr !== ''){
      console.log(stderr.red); 
    }
  });
}catch(err){
  console.log(err.red); 
}
